version: '3.8'

services:
  proxy-dipsy:
    build: .
    ports:
      - "3232:3232"
    environment:
      - PORT=8080
    restart: unless-stopped
    volumes:
      - ./:/app
    command: sh -c "go build -o /proxy-dipsy && /proxy-dipsy"