version: '3.8'

services:
  deepseek-proxy:
    build: .
    ports:
      - "3232:3232"
    environment:
      - PORT=3232
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
    restart: unless-stopped
    volumes:
      - ./:/app